# Generated by Django 2.2.1 on 2019-08-13 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stickandpuck', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stickandpuckskaters',
            options={'ordering': ['guardian']},
        ),
        migrations.AlterField(
            model_name='stickandpuckdates',
            name='session_end_time',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='stickandpuckdates',
            name='session_start_time',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterUniqueTogether(
            name='stickandpuckskaters',
            unique_together={('first_name', 'last_name', 'date_of_birth')},
        ),
    ]
