# Generated by Django 2.2.1 on 2019-08-13 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stickandpuck', '0002_auto_20190813_1458'),
    ]

    operations = [
        migrations.AddField(
            model_name='stickandpucksessions',
            name='session_time',
            field=models.CharField(default='blah', max_length=10),
            preserve_default=False,
        ),
    ]
