# Generated by Django 2.2.1 on 2019-08-13 22:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stickandpuck', '0003_stickandpucksessions_session_time'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='stickandpucksessions',
            unique_together={('skater', 'session_date', 'session_time')},
        ),
    ]
