# Generated by Django 2.2.1 on 2019-08-14 16:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stickandpuck', '0004_auto_20190813_1743'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stickandpucksessions',
            options={'ordering': ['-session_date', 'session_time']},
        ),
        migrations.AlterUniqueTogether(
            name='stickandpuckdates',
            unique_together={('session_date', 'session_start_time', 'session_end_time')},
        ),
    ]
