# Generated by Django 2.2.1 on 2019-08-14 17:53

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('stickandpuck', '0005_auto_20190814_1126'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='stickandpucksessions',
            unique_together={('guardian', 'skater', 'session_date', 'session_time')},
        ),
        migrations.AlterUniqueTogether(
            name='stickandpuckskaters',
            unique_together={('guardian', 'first_name', 'last_name', 'date_of_birth')},
        ),
    ]
