# Generated by Django 2.2.1 on 2019-10-08 23:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stickandpuck', '0006_auto_20190814_1253'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stickandpuckdates',
            options={'ordering': ['-session_date']},
        ),
    ]
