# Generated by Django 2.2.1 on 2020-06-18 13:21

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('stickandpuck', '0008_auto_20200221_0935'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='StickAndPuckDates',
            new_name='StickAndPuckDate',
        ),
        migrations.RenameModel(
            old_name='StickAndPuckSessions',
            new_name='StickAndPuckSession',
        ),
        migrations.RenameModel(
            old_name='StickAndPuckSkaters',
            new_name='StickAndPuckSkater',
        ),
    ]
