# Generated by Django 2.2.1 on 2019-07-23 15:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('open_hockey', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='openhockeysessions',
            options={'ordering': ['-date']},
        ),
        migrations.CreateModel(
            name='OpenHockeyMember',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('end_date', models.DateField()),
                ('active', models.BooleanField(default=True)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-end_date'],
            },
        ),
    ]
