# Generated by Django 2.2.1 on 2019-07-23 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('open_hockey', '0002_auto_20190723_1025'),
    ]

    operations = [
        migrations.AlterField(
            model_name='openhockeymember',
            name='active',
            field=models.BooleanField(),
        ),
    ]
