# Generated by Django 2.2.1 on 2019-07-25 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('open_hockey', '0004_auto_20190725_1203'),
    ]

    operations = [
        migrations.AddField(
            model_name='openhockeysessions',
            name='paid',
            field=models.BooleanField(default=False),
        ),
    ]
