# Generated by Django 2.2.1 on 2019-10-08 23:38

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('open_hockey', '0005_openhockeysessions_paid'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='openhockeymember',
            unique_together={('member',)},
        ),
    ]
