# Generated by Django 2.2.1 on 2020-02-09 18:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('open_hockey', '0006_auto_20191008_1838'),
    ]

    operations = [
        migrations.CreateModel(
            name='OpenHockeyMemberType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('cost', models.IntegerField()),
                ('duration', models.IntegerField(help_text='Number of Days')),
            ],
        ),
        migrations.AddField(
            model_name='openhockeymember',
            name='member_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='open_hockey.OpenHockeyMemberType'),
        ),
    ]
