# Generated by Django 2.2.1 on 2020-02-07 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0002_paymenterror'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='square_receipt',
            field=models.CharField(default='PX20', max_length=100),
            preserve_default=False,
        ),
    ]
