# Generated by Django 3.2.25 on 2025-12-28 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0005_auto_20200226_1348'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymenterror',
            name='error',
            field=models.TextField(),
        ),
    ]
