# Generated by Django 4.0.10 on 2026-09-21 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0006_alter_paymenterror_error'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='square_receipt',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
