# Generated by Django 2.2.1 on 2020-07-17 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message_boards', '0002_board_slug'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='board',
            options={'ordering': ['pk']},
        ),
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['created_at']},
        ),
        migrations.AlterModelOptions(
            name='topic',
            options={'ordering': ['-last_updated']},
        ),
        migrations.AddField(
            model_name='topic',
            name='sticky',
            field=models.BooleanField(default=False),
        ),
    ]
