# Generated by Django 2.2.1 on 2020-07-17 19:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('message_boards', '0003_auto_20200717_1223'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='topic',
            options={'ordering': ['-sticky', '-last_updated']},
        ),
    ]
