# Generated by Django 2.2.1 on 2020-07-17 19:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
        ('message_boards', '0004_auto_20200717_1426'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='auth.Group'),
        ),
        migrations.AlterField(
            model_name='topic',
            name='subject',
            field=models.CharField(max_length=60),
        ),
    ]
