# Generated by Django 2.2.1 on 2020-08-31 17:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lady_hawks', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ladyhawksskatedate',
            options={'ordering': ['skate_date'], 'verbose_name_plural': 'Lady Hawks Skate Dates'},
        ),
        migrations.AlterModelOptions(
            name='ladyhawksskatesession',
            options={'ordering': ['-skate_date'], 'verbose_name_plural': 'Lady Hawks Skate Sessions'},
        ),
    ]
