# Generated by Django 2.2.1 on 2020-02-23 11:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('thane_storck', '0002_auto_20200222_1640'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skatesession',
            name='skate_date',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='session_skaters', to='thane_storck.SkateDate'),
        ),
    ]
