# Generated by Django 2.2.1 on 2020-06-24 09:48

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mike_schultz', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mikeschultzskatesession',
            old_name='skater',
            new_name='user',
        ),
        migrations.AlterUniqueTogether(
            name='mikeschultzskatesession',
            unique_together={('user', 'skate_date')},
        ),
    ]
