# Generated by Django 2.2.1 on 2020-06-24 14:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_childskater'),
        ('mike_schultz', '0002_auto_20200624_0448'),
    ]

    operations = [
        migrations.AddField(
            model_name='mikeschultzskatesession',
            name='skater',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.ChildSkater'),
        ),
    ]
