# Generated by Django 2.2.1 on 2020-06-24 14:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_childskater'),
        ('mike_schultz', '0003_mikeschultzskatesession_skater'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='mikeschultzskatesession',
            unique_together={('skater', 'skate_date')},
        ),
    ]
