# Generated by Django 2.2.1 on 2020-06-24 14:58

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0014_childskater'),
        ('mike_schultz', '0004_auto_20200624_0953'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='mikeschultzskatesession',
            unique_together={('user', 'skater', 'skate_date')},
        ),
    ]
