# Generated by Django 2.2.1 on 2020-02-13 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20200213_1340'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='slug',
            field=models.SlugField(default='user', unique=True),
            preserve_default=False,
        ),
    ]
