# Generated by Django 2.2.1 on 2020-02-14 18:07

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0004_profile_slug'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='profile',
            unique_together={('user', 'slug')},
        ),
    ]
