# Generated by Django 2.2.1 on 2020-02-25 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20200214_1207'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='thane_storck_email',
            field=models.BooleanField(default=False),
        ),
    ]
