# Generated by Django 2.2.1 on 2020-06-05 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_profile_thane_storck_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='release_of_liability',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='release_of_liability_date_signed',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
