# Generated by Django 2.2.1 on 2020-06-05 16:09

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0009_releaseofliability'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='releaseofliability',
            unique_together={('user', 'release_of_liability')},
        ),
    ]
