# Generated by Django 2.2.1 on 2020-06-09 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_auto_20200605_1109'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='adult_skills_email',
            field=models.BooleanField(default=False),
        ),
    ]
