# Generated by Django 2.2.1 on 2020-06-10 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_profile_adult_skills_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='mike_schultz_email',
            field=models.BooleanField(default=False),
        ),
    ]
