# Generated by Django 2.2.1 on 2020-06-24 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_auto_20200624_1347'),
    ]

    operations = [
        migrations.AlterField(
            model_name='childskater',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
    ]
