# Generated by Django 2.2.1 on 2020-07-06 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_auto_20200624_1349'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='womens_hockey_email',
            field=models.BooleanField(default=False),
        ),
    ]
