# Generated by Django 2.2.1 on 2020-07-21 17:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0019_auto_20200720_0910'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercredit',
            name='slug',
            field=models.SlugField(default='blank', unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='usercredit',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='usercredit',
            unique_together={('user', 'slug')},
        ),
    ]
