# Generated by Django 2.2.1 on 2020-07-21 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0020_auto_20200721_1236'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercredit',
            name='paid',
            field=models.BooleanField(default=False),
        ),
    ]
