# Generated by Django 2.2.1 on 2020-07-22 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0021_usercredit_paid'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercredit',
            name='pending',
            field=models.PositiveIntegerField(default=0, null=True),
        ),
    ]
