# Generated by Django 2.2.1 on 2020-08-27 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0022_usercredit_pending'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='bald_eagles_email',
            field=models.BooleanField(default=False),
        ),
    ]
