# Generated by Django 2.2.1 on 2020-11-25 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0024_profile_lady_hawks_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='chs_alumni_email',
            field=models.BooleanField(default=False),
        ),
    ]
