# Generated by Django 2.2.23 on 2021-11-01 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0026_auto_20210317_0901'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='kranich_email',
            field=models.BooleanField(default=False),
        ),
    ]
