# Generated by Django 2.2.23 on 2022-02-10 16:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0028_profile_caribou_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='caribou_email',
            new_name='nacho_skate_email',
        ),
    ]
