# Generated by Django 2.2.23 on 2022-04-07 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0029_auto_20220210_1012'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='ament_email',
            field=models.BooleanField(default=False),
        ),
    ]
