# Generated by Django 2.2.1 on 2020-08-27 17:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bald_eagles', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='baldeaglessession',
            options={'ordering': ['-session_date'], 'verbose_name_plural': 'Bald Eagles sessions'},
        ),
        migrations.AlterModelOptions(
            name='baldeaglesskatedate',
            options={'ordering': ['skate_date'], 'verbose_name_plural': 'Bald Eagles skate dates'},
        ),
        migrations.AlterField(
            model_name='baldeaglessession',
            name='skater',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skaters', to=settings.AUTH_USER_MODEL),
        ),
    ]
