# Generated by Django 2.2.1 on 2020-03-12 15:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FigureSkater',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=25)),
                ('last_name', models.CharField(max_length=50)),
                ('date_of_birth', models.DateField(blank=True)),
                ('guardian', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['guardian'],
                'unique_together': {('guardian', 'first_name', 'last_name', 'date_of_birth')},
            },
        ),
        migrations.CreateModel(
            name='FigureSkatingDate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skate_date', models.DateField()),
                ('start_time', models.CharField(max_length=10)),
                ('end_time', models.CharField(max_length=10)),
            ],
            options={
                'ordering': ['skate_date'],
                'unique_together': {('skate_date', 'start_time', 'end_time')},
            },
        ),
        migrations.CreateModel(
            name='FigureSkatingSession',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paid', models.BooleanField(default=False)),
                ('guardian', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='figure_skating.FigureSkatingDate')),
                ('skater', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='figure_skating.FigureSkater')),
            ],
        ),
    ]
