# Generated by Django 2.2.1 on 2020-07-21 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('figure_skating', '0003_figureskatingdate_available_spots'),
    ]

    operations = [
        migrations.AddField(
            model_name='figureskatingdate',
            name='up_down_charge',
            field=models.IntegerField(default=0, help_text='Enter positive number for up charge, negative number for down charge.'),
        ),
    ]
