# Generated by Django 3.2.13 on 2022-07-06 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('figure_skating', '0005_auto_20210411_0940'),
    ]

    operations = [
        migrations.AddField(
            model_name='figureskatingdate',
            name='low_level',
            field=models.BooleanField(default=False),
        ),
    ]
