# Generated by Django 2.2.1 on 2019-10-08 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RinkSchedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('rink', models.CharField(max_length=15)),
                ('event', models.CharField(max_length=50)),
                ('notes', models.CharField(max_length=50)),
            ],
        ),
    ]
