# Generated by Django 2.2.1 on 2019-10-09 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0002_rinkschedule_schedule_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rinkschedule',
            name='notes',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
