# Generated by Django 2.2.1 on 2019-10-09 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0003_auto_20191008_1916'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rinkschedule',
            name='notes',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
