# Generated by Django 2.2.23 on 2021-09-22 13:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0006_auto_20210318_1006'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rinkschedule',
            options={'ordering': ['end_time'], 'verbose_name_plural': 'Rink Schedule'},
        ),
        migrations.AlterUniqueTogether(
            name='rinkschedule',
            unique_together={('schedule_date', 'start_time', 'end_time', 'rink')},
        ),
    ]
