# Generated by Django 3.2.13 on 2025-10-23 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0007_auto_20210922_0839'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rinkschedule',
            name='event',
            field=models.CharField(help_text="Field format for two teams: Put home team first and separate with ' vs ', a space then, lowercase vs, then a space", max_length=100),
        ),
    ]
