# Generated by Django 3.2.25 on 2025-12-20 16:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('schedule', '0008_alter_rinkschedule_event'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduleIngestRun',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_dt', models.DateTimeField(auto_now_add=True)),
                ('updated_dt', models.DateTimeField(auto_now=True)),
                ('run_id', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('triggered_by', models.CharField(help_text='manual | scheduled | preview | rollback', max_length=50)),
                ('dry_run', models.BooleanField(default=False)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('success', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='LockerRoomRule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_dt', models.DateTimeField(auto_now_add=True)),
                ('updated_dt', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
                ('priority', models.IntegerField(help_text='Lower number = higher priority')),
                ('rink', models.CharField(help_text='North, South, or Any', max_length=20)),
                ('event_type', models.CharField(blank=True, help_text='Optional match on event type (e.g. Game)', max_length=50)),
                ('team_contains', models.CharField(blank=True, help_text='Substring match on team/event name', max_length=100)),
                ('home_locker_room', models.CharField(blank=True, max_length=10)),
                ('visitor_locker_room', models.CharField(blank=True, max_length=10)),
                ('lock_during_games', models.BooleanField(default=True, help_text='Prevent edits during active games')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['priority'],
            },
        ),
        migrations.CreateModel(
            name='ScheduleRunAcknowledgment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acknowledged_at', models.DateTimeField(auto_now_add=True)),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='acknowledgments', to='schedule.scheduleingestrun')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('run', 'user')},
            },
        ),
        migrations.CreateModel(
            name='RinkScheduleSnapshot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_dt', models.DateTimeField(auto_now_add=True)),
                ('updated_dt', models.DateTimeField(auto_now=True)),
                ('schedule_date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('rink', models.CharField(max_length=50)),
                ('event', models.CharField(max_length=255)),
                ('home_locker_room', models.CharField(blank=True, max_length=10)),
                ('visitor_locker_room', models.CharField(blank=True, max_length=10)),
                ('locker_reason', models.TextField()),
                ('locker_evaluation', models.JSONField(default=list)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='snapshots', to='schedule.scheduleingestrun')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['schedule_date', 'start_time'],
                'unique_together': {('run', 'schedule_date', 'start_time', 'rink')},
            },
        ),
    ]
