# Generated by Django 3.2.25 on 2025-12-20 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0009_lockerroomrule_rinkschedulesnapshot_scheduleingestrun_schedulerunacknowledgment'),
    ]

    operations = [
        migrations.CreateModel(
            name='NameNormalizationRule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('priority', models.PositiveIntegerField(help_text='Lower number = higher priority')),
                ('match_text', models.CharField(help_text='Substring to match (case-insensitive)', max_length=255)),
                ('replace_with', models.CharField(help_text='Replacement text', max_length=255)),
                ('active', models.BooleanField(default=True)),
                ('created_by', models.CharField(blank=True, max_length=150)),
                ('created_dt', models.DateTimeField(auto_now_add=True)),
                ('updated_by', models.CharField(blank=True, max_length=150)),
                ('updated_dt', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['priority'],
            },
        ),
    ]
