# Generated by Django 3.2.25 on 2025-12-20 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0010_namenormalizationrule'),
    ]

    operations = [
        migrations.AlterField(
            model_name='namenormalizationrule',
            name='replace_with',
            field=models.CharField(blank=True, default='', help_text='Replacement text (leave blank to delete)', max_length=255),
        ),
    ]
