# Generated by Django 3.2.25 on 2025-12-21 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0011_alter_namenormalizationrule_replace_with'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lockerroomrule',
            options={},
        ),
        migrations.RemoveField(
            model_name='lockerroomrule',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='lockerroomrule',
            name='created_dt',
        ),
        migrations.RemoveField(
            model_name='lockerroomrule',
            name='event_type',
        ),
        migrations.RemoveField(
            model_name='lockerroomrule',
            name='lock_during_games',
        ),
        migrations.RemoveField(
            model_name='lockerroomrule',
            name='updated_by',
        ),
        migrations.RemoveField(
            model_name='lockerroomrule',
            name='updated_dt',
        ),
        migrations.AddField(
            model_name='lockerroomrule',
            name='alt_home_locker_room',
            field=models.CharField(blank=True, max_length=5),
        ),
        migrations.AddField(
            model_name='lockerroomrule',
            name='alt_visitor_locker_room',
            field=models.CharField(blank=True, max_length=5),
        ),
        migrations.AlterField(
            model_name='lockerroomrule',
            name='home_locker_room',
            field=models.CharField(blank=True, max_length=5),
        ),
        migrations.AlterField(
            model_name='lockerroomrule',
            name='priority',
            field=models.IntegerField(default=100),
        ),
        migrations.AlterField(
            model_name='lockerroomrule',
            name='rink',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='lockerroomrule',
            name='team_contains',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='lockerroomrule',
            name='visitor_locker_room',
            field=models.CharField(blank=True, max_length=5),
        ),
    ]
