# Generated by Django 3.2.25 on 2025-12-21 20:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('schedule', '0012_auto_20251221_1402'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lockerroomrule',
            options={'ordering': ['priority']},
        ),
        migrations.RemoveField(
            model_name='lockerroomrule',
            name='alt_home_locker_room',
        ),
        migrations.RemoveField(
            model_name='lockerroomrule',
            name='alt_visitor_locker_room',
        ),
        migrations.AddField(
            model_name='lockerroomrule',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='lockerroomrule',
            name='created_dt',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lockerroomrule',
            name='event_type',
            field=models.CharField(blank=True, help_text='Optional match on event type (e.g. Game)', max_length=50),
        ),
        migrations.AddField(
            model_name='lockerroomrule',
            name='lock_during_games',
            field=models.BooleanField(default=True, help_text='Prevent edits during active games'),
        ),
        migrations.AddField(
            model_name='lockerroomrule',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='lockerroomrule',
            name='updated_dt',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='lockerroomrule',
            name='home_locker_room',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='lockerroomrule',
            name='priority',
            field=models.IntegerField(help_text='Lower number = higher priority'),
        ),
        migrations.AlterField(
            model_name='lockerroomrule',
            name='rink',
            field=models.CharField(help_text='North, South, or Any', max_length=20),
        ),
        migrations.AlterField(
            model_name='lockerroomrule',
            name='team_contains',
            field=models.CharField(blank=True, help_text='Substring match on team/event name', max_length=100),
        ),
        migrations.AlterField(
            model_name='lockerroomrule',
            name='visitor_locker_room',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
