# Generated by Django 2.2.1 on 2020-02-21 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProgramDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('program_name', models.CharField(max_length=100, unique=True)),
                ('max_skaters', models.IntegerField(blank=True, default=22, null=True)),
                ('max_goalies', models.IntegerField(blank=True, null=True)),
                ('skater_price', models.IntegerField(blank=True, null=True)),
                ('goalie_price', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
