# Generated by Django 2.2.1 on 2020-02-21 19:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProgramDetail',
            new_name='Program',
        ),
    ]
