# Generated by Django 2.2.1 on 2020-07-23 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0003_auto_20200222_1444'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserCreditIncentive',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price_point', models.PositiveSmallIntegerField(help_text='The price at which the incentive kicks in.')),
                ('incentive', models.PositiveSmallIntegerField(help_text='Percentage of free credits for this price point. Enter as whole number.')),
            ],
            options={
                'ordering': ['-price_point'],
            },
        ),
    ]
