# Generated by Django 2.2.1 on 2021-02-18 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0004_usercreditincentive'),
    ]

    operations = [
        migrations.AddField(
            model_name='program',
            name='description',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='program',
            name='private',
            field=models.BooleanField(default=False, help_text='If checked, this program will not be shown to the public.'),
        ),
        migrations.AddField(
            model_name='program',
            name='special_message',
            field=models.CharField(blank=True, help_text='Used for special messages, will be displayed as bold in colored info box.', max_length=200, null=True),
        ),
    ]
