# Generated by Django 2.2.1 on 2021-02-18 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0005_auto_20210218_0820'),
    ]

    operations = [
        migrations.RenameField(
            model_name='program',
            old_name='special_message',
            new_name='message',
        ),
    ]
