# Generated by Django 2.2.1 on 2021-02-18 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0006_auto_20210218_0823'),
    ]

    operations = [
        migrations.AddField(
            model_name='program',
            name='days_and_times',
            field=models.CharField(default='Check OICWebApps for days/times', max_length=100),
        ),
        migrations.AlterField(
            model_name='program',
            name='description',
            field=models.TextField(blank=True, help_text='Max 400 characters', max_length=400, null=True),
        ),
    ]
