# Generated by Django 2.2.1 on 2020-03-20 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='event_start_time',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='cart',
            name='time_stamp',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
