# Generated by Django 2.2.1 on 2020-11-25 18:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chs_alumni', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chsalumnidate',
            options={'ordering': ['skate_date'], 'verbose_name': 'CHS Alumni date'},
        ),
        migrations.AlterModelOptions(
            name='chsalumnisession',
            options={'ordering': ['-date'], 'verbose_name': 'CHS Alumni session'},
        ),
        migrations.AlterField(
            model_name='chsalumnisession',
            name='date',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='session_skaters', to='chs_alumni.CHSAlumniDate'),
        ),
    ]
