# Generated by Django 2.2.1 on 2021-02-25 18:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0025_profile_chs_alumni_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrivateSkate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=75, unique=True)),
                ('max_skaters', models.IntegerField(blank=True, default=None, help_text='If no maximum, leave blank!', null=True)),
                ('max_goalies', models.IntegerField(blank=True, default=None, help_text='If no maximum, leave blank!', null=True)),
                ('skater_price', models.IntegerField(default=12)),
                ('goalie_price', models.IntegerField(default=0)),
                ('slug', models.SlugField(max_length=75)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='PrivateSkateDate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('private_skate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='private_skates.PrivateSkate')),
            ],
            options={
                'ordering': ['date'],
                'unique_together': {('private_skate', 'date')},
            },
        ),
        migrations.CreateModel(
            name='PrivateSkateSession',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goalie', models.BooleanField(default=False)),
                ('paid', models.BooleanField(default=False)),
                ('skate_date', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='private_skates.PrivateSkateDate')),
                ('skater', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.ChildSkater')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-skate_date'],
                'unique_together': {('skater', 'skate_date')},
            },
        ),
    ]
