# Generated by Django 2.2.1 on 2021-03-17 14:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0026_auto_20210317_0901'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('private_skates', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='privateskate',
            name='slug',
            field=models.SlugField(help_text='CREATE A NEW GROUP IN AUTHENTICATION AND AUTHORIZATION WITH THIS SLUG!!!!', max_length=75),
        ),
        migrations.AlterField(
            model_name='privateskatedate',
            name='private_skate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skate_dates', to='private_skates.PrivateSkate'),
        ),
        migrations.AlterField(
            model_name='privateskatesession',
            name='skate_date',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='session_skaters', to='private_skates.PrivateSkateDate'),
        ),
        migrations.AlterUniqueTogether(
            name='privateskatesession',
            unique_together={('user', 'skater', 'skate_date')},
        ),
    ]
