# Generated by Django 2.2.1 on 2021-03-18 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('private_skates', '0002_auto_20210317_0901'),
    ]

    operations = [
        migrations.AlterField(
            model_name='privateskate',
            name='max_goalies',
            field=models.IntegerField(blank=True, default=None, help_text='If no maximum, leave blank! Enter 0 for no goalies.', null=True),
        ),
        migrations.AlterField(
            model_name='privateskate',
            name='max_skaters',
            field=models.IntegerField(blank=True, default=None, help_text='If no maximum, leave blank! Enter 0 for no skaters.', null=True),
        ),
    ]
