# Generated by Django 2.2.23 on 2021-10-24 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('how_to_videos', '0002_auto_20211022_1112'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(default=None, help_text='DO NOT CHANGE THIS FIELD!', max_length=100),
        ),
    ]
