# Generated by Django 2.2.23 on 2021-10-24 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('how_to_videos', '0003_auto_20211024_1051'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='staff_only',
            field=models.BooleanField(default=False),
        ),
    ]
